/** Append-only audit event types. */
export const AUDIT_EVENT = {
  INVITATION_CREATED: "invitation_created",
  INVITATION_SENT: "invitation_sent",
  INVITATION_OPENED: "invitation_opened",
  NOTIFICATION_QUEUED: "notification_queued",
  NOTIFICATION_SENT: "notification_sent",
  NOTIFICATION_FAILED: "notification_failed",
  CONTACT_CREATED: "contact_created",
  CONTACT_UPDATED: "contact_updated",
  CONTACT_ARCHIVED: "contact_archived",
  CONTACT_RESTORED: "contact_restored",
  CONTACT_DELETED: "contact_deleted",
  CONTACT_REASSIGNED: "contact_reassigned",
  LEGAL_EVIDENCE_CREATED: "legal_evidence_created",
  LEGAL_EVIDENCE_EXPORTED: "legal_evidence_exported",
  PRESENTATION_DELETED: "presentation_deleted",
  LEGAL_DISPLAYED: "legal_displayed",
  LEGAL_ACCEPTED: "legal_accepted",
  LEGAL_DOCUMENT_VIEWED: "legal_document_viewed",
  VIDEO_UPLOADED: "video_uploaded",
  VIDEO_ACTIVATED: "video_activated",
  VIDEO_DEACTIVATED: "video_deactivated",
  VIDEO_ARCHIVED: "video_archived",
  VIDEO_DELETED: "video_deleted",
  VIDEO_RESTORED: "video_restored",
  VIDEO_OPTIMIZATION_REQUESTED: "video_optimization_requested",
  VIDEO_REPROCESS_REQUESTED: "video_reprocess_requested",
  VIDEO_BULK_OPTIMIZATION_REQUESTED: "video_bulk_optimization_requested",
  VIDEO_DELETION_SCHEDULED: "video_deletion_scheduled",
  VIDEO_DELETION_POSTPONED: "video_deletion_postponed",
  VIDEO_PERMANENTLY_DELETED: "video_permanently_deleted",
  VIDEO_DELETION_FAILED: "video_deletion_failed",
  VIDEO_PLAYBACK_ASSET_ACTIVATED: "video_playback_asset_activated",
  VIDEO_PROCESSING_FAILED: "video_processing_failed",
  VIDEO_PROCESSING_STALE_RECOVERED: "video_processing_stale_recovered",
  VIDEO_PROCESSING_JOB_DISPATCHED: "video_processing_job_dispatched",
  VIDEO_STARTED: "video_started",
  PLAYBACK_PROGRESS: "playback_progress",
  VIDEO_COMPLETED: "video_completed",
  SESSION_CLOSED: "session_closed",
  FAILED_ACCESS_ATTEMPT: "failed_access_attempt",
  REPRESENTATIVE_ACTION: "representative_action",
  ADMINISTRATOR_ACTION: "administrator_action",
  FOLLOWUP_SCHEDULED: "followup_scheduled",
  FOLLOWUP_COMPLETED: "followup_completed",
  EMAIL_SENT: "email_sent",
  EMAIL_FAILED: "email_failed",
  SESSION_RESET: "session_reset",
  DEVICE_RESET: "device_reset",
  USER_UPDATED: "user_updated",
  USER_EMAIL_CHANGED: "user_email_changed",
  USER_ROLE_CHANGED: "user_role_changed",
  USER_DEACTIVATED: "user_deactivated",
  USER_REACTIVATED: "user_reactivated",
  USER_DELETED: "user_deleted",
  USER_PRESENTATION_ASSIGNMENT_CHANGED: "user_presentation_assignment_changed",
  USER_ACCESS_POLICY_CHANGED: "user_access_policy_changed",
} as const;

export type AuditEventType =
  (typeof AUDIT_EVENT)[keyof typeof AUDIT_EVENT];

/** Analytics metric keys stored on session.analytics and analyticsEvents. */
export const ANALYTICS_METRIC = {
  INVITATION_SENT_AT: "invitationSentAt",
  INVITATION_OPENED_AT: "invitationOpenedAt",
  TIME_UNTIL_NDA_MS: "timeUntilNdaMs",
  TIME_UNTIL_VIDEO_START_MS: "timeUntilVideoStartMs",
  WATCH_DURATION_MS: "watchDurationMs",
  COMPLETION_PERCENT: "completionPercent",
  COMPLETION_TIME: "completionTime",
  FOLLOWUP_SCHEDULED_AT: "followupScheduledAt",
  FOLLOWUP_COMPLETED_AT: "followupCompletedAt",
} as const;
